# Form implementation generated from reading ui file 'e:\IOT\Projects\Python\GPSTrackEditor\gui\slider_filter.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SliderFilter(object):
    def setupUi(self, SliderFilter):
        SliderFilter.setObjectName("SliderFilter")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SliderFilter.sizePolicy().hasHeightForWidth())
        SliderFilter.setSizePolicy(sizePolicy)
        SliderFilter.setAccessibleName("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(SliderFilter)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBoxRangeMin = QtWidgets.QSpinBox(parent=SliderFilter)
        self.spinBoxRangeMin.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBoxRangeMin.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBoxRangeMin.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBoxRangeMin.setMinimum(0)
        self.spinBoxRangeMin.setMaximum(999999)
        self.spinBoxRangeMin.setProperty("value", 0)
        self.spinBoxRangeMin.setObjectName("spinBoxRangeMin")
        self.horizontalLayout.addWidget(self.spinBoxRangeMin)
        self.sliderFilter = QtWidgets.QSlider(parent=SliderFilter)
        self.sliderFilter.setMinimum(1)
        self.sliderFilter.setMaximum(100)
        self.sliderFilter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sliderFilter.setObjectName("sliderFilter")
        self.horizontalLayout.addWidget(self.sliderFilter)
        self.spinBoxRangeMax = QtWidgets.QSpinBox(parent=SliderFilter)
        self.spinBoxRangeMax.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBoxRangeMax.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBoxRangeMax.setMinimum(0)
        self.spinBoxRangeMax.setMaximum(999999)
        self.spinBoxRangeMax.setProperty("value", 0)
        self.spinBoxRangeMax.setObjectName("spinBoxRangeMax")
        self.horizontalLayout.addWidget(self.spinBoxRangeMax)

        self.retranslateUi(SliderFilter)
        QtCore.QMetaObject.connectSlotsByName(SliderFilter)

    def retranslateUi(self, SliderFilter):
        _translate = QtCore.QCoreApplication.translate
        SliderFilter.setWindowTitle(_translate("SliderFilter", "SliderFilter"))
